[[plugin]]
name = "gpu-monitor"
version = "1.0.0"
description = "Monitors GPU utilization and memory"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/gpu-monitor-1.0.0.tar.gz"
checksum = "1d0346b47f44f178795486725179285da678033053b179f3958bc433dadea99e"

[[plugin]]
name = "temperature"
version = "1.0.0"
description = "Monitors CPU thermal zones"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/temperature-1.0.0.tar.gz"
checksum = "33a746461b766a8781269e5b2ad02501a3a693b8ab0512d65f8db3260e1076af"

[[plugin]]
name = "docker-stats"
version = "1.0.0"
description = "Monitors active Docker containers"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/docker-stats-1.0.0.tar.gz"
checksum = "3556646ac592c56dd35b6dc3a93446b961cfe87f7d5a1c170abe0fb719f89490"

[[plugin]]
name = "network-latency"
version = "1.0.0"
description = "Monitors ping latency to Google"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/network-latency-1.0.0.tar.gz"
checksum = "b5b154620f4bbfdfc46561440b739483a9290ad10c226660a4cf766e9742fb51"
