[[plugin]]
name = "gpu-monitor"
version = "1.0.0"
description = "Monitors GPU utilization and memory"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/gpu-monitor-1.0.0.tar.gz"
checksum = "b5132328ce1f78b971964f18f98483ea9932a8521a11f3e0b704f5bfbb000279"

[[plugin]]
name = "temperature"
version = "1.0.0"
description = "Monitors CPU thermal zones"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/temperature-1.0.0.tar.gz"
checksum = "8404d863dff49c7f36017c0c5dce800d09754d13baf917ad9d5c46afbecb4c48"

[[plugin]]
name = "docker-stats"
version = "1.0.0"
description = "Monitors active Docker containers"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/docker-stats-1.0.0.tar.gz"
checksum = "3201cc5ca7008b20bfc9cf020dd8626cb9eb2f3f7312d327a1986a574615d9e3"

[[plugin]]
name = "network-latency"
version = "1.0.0"
description = "Monitors ping latency to Google"
url = "https://raw.githubusercontent.com/mukundangopalachary/sysmon/master/registry/packages/network-latency-1.0.0.tar.gz"
checksum = "a29eeb17384a2b64828c1b27be3b4bd93c1b8cf0fcbc05baf26c2545be4f46d2"
